kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: chubaofs-sc
provisioner: csi.chubaofs.com
reclaimPolicy: Delete
parameters:
  masterAddr: "master-service.chubaofs.svc.cluster.local:17010"
  owner: "csiuser"
  # cannot set profPort and exporterPort value, reason: a node may be run many cfs-client
  #  profPort: "10094"
  #  exporterPort: "9513"
  consulAddr: "consul-service.chubaofs.svc.cluster.local:8500"
  logLevel: "debug"
